#!/bin/bash

DAT="/scr/raf_data/MAIRE24"
homedir=~

project="MAIRE24"
Directory="${DAT}"

# Default lat/lon to roughly Colorado. Must be set for each project. This is
# the area for which the Terrain database will be downloaded. Set to minimum
# area needed to speed up processing and save disk space.
area=$(flt_area ${DAT}/${project}[rt]f??.nc | tail -4)
lt_s=$(printf '%.0f' $(echo $area | awk '{print $6}'))
lt_n=$(printf '%.0f' $(echo $area | awk '{print $3}'))
lg_w=$(printf '%.0f' $(echo $area | awk '{print $9}'))
lg_e=$(printf '%.0f' $(echo $area | awk '{print $12}'))

# Set Tdb to yes the first time this is run to download the Terrain database.
# Set to no after first run to save time.
Tdb="yes"

# Expand everything out a degree to ensure we don't lose any edge data.
lt_s=$((lt_s - 1))
lt_n=$((lt_n + 1))
lg_w=$((lg_w - 1))
lg_e=$((lg_e + 1))

echo "Adding Terrain Ht vars to netCDF files in ${DAT} for project ${project}"
echo "Using lat/long range ${lt_s} - ${lt_n}, ${lg_w} - ${lg_e}"

for file in ${Directory}/${project}[rtf]f??.nc; do
    flight=$(basename ${file} | grep -oP '[rtf]f\d{2}')
    echo "python ./HeightOfTerrain.py ${project} ${flight} ${Directory} ${lt_s} ${lt_n} ${lg_w} ${lg_e} ${Tdb}"
    # Uncomment the following line to actually run the script
    python ./HtOfTerrain.py ${project} ${flight} ${Directory} ${lt_s} ${lt_n} ${lg_w} ${lg_e} ${Tdb}
done
